In [1]:
names = ['Yusra','Ayesha','Jaweria']

In [2]:
for i in names:
    print(i)

Yusra
Ayesha
Jaweria


In [10]:
for i in range(len(names)):
    print(names[i])

Yusra
Ayesha
Jaweria


In [6]:
import math

In [11]:
import pandas as pd

In [1]:
x = 2
while x> 0:
    print("meow")
    x = x-1

meow
meow


In [7]:
x = [2,1,3]
print(x)
x.sort()
print(x)
print(x[1:])

[2, 1, 3]
[1, 2, 3]
[2, 3]


In [6]:
x = (2,1,3)
print(x)
print(x[1:])

(2, 1, 3)
(1, 3)


In [10]:
x = {2,1,3,5,2,1}
print(x)

{1, 2, 3, 5}


In [11]:
x = {1,2,4}
y = [3,5,6]
x.update(y)
print(x)

{1, 2, 3, 4, 5, 6}


In [12]:
dict = {
    "name" : "yusra",
    "id" : 234
}
print(type(dict))
print(dict["id"])

<class 'dict'>
234


In [18]:
num1 = int(input("Enter ist num: "))
num2 = int(input("Enter second num: "))
num = num1 + num2
print("Sum: " + str(num))

Enter ist num:  4
Enter second num:  4


Sum: 8


In [27]:
dict = {
    "Yusra" : 99,
    "Alison" : 76,
    "Luffy" : 2
}
for key in dict:
    print(key)
for i in dict.values():
    print(i)
print(dict["Yusra"])

Yusra
Alison
Luffy
99
76
2
99


In [37]:
marks = {
    "Yusra": [22, 88, 95],
    "Hafsa": [70, 75, 80],
    "Maria": [98, 82, 91],
}
avg = {}
for key in marks.keys():
    avg[key] = 0
for key,value in marks.items():
    sum = 0
    for i in value:
        sum = sum + i
    num = sum/300
    avg[key] = num
print(avg)
print("Top Performer: ")
print(max(avg, key= avg.get))

{'Yusra': 0.6833333333333333, 'Hafsa': 0.75, 'Maria': 0.9033333333333333}
Top Performer: 
Maria


In [51]:
cities = ["Sukkur", "Karachi", "Islamabad", "Karachi", "Quetta", "Sukkur", "Sukkur"]
new_list = []
new_list.append(cities[0])
for city1 in range(1,len(cities)):
    check = False
    for city2 in new_list:
        if (cities[city1] == city2):
            check = True
    if(check == False):
        new_list.append(cities[city1])
print(new_list)

#second easy skip
new_list.insert(2,"Lahore")
print(new_list)

['Sukkur', 'Karachi', 'Islamabad', 'Quetta']
['Sukkur', 'Karachi', 'Lahore', 'Islamabad', 'Quetta']


In [65]:
students = {
    "Yusra":  {"marks": [55, 88, 92], "city": "Sukkur"},
    "Hafsa":  {"marks": [70, 75, 80], "city": "Karachi"},
    "Maria":  {"marks": [98, 82, 91], "city": "Karachi"},
    "Sadia":  {"marks": [40, 35, 50], "city": "Sukkur"},
    "Ali":    {"marks": [90, 95, 100], "city": "Islamabad"}
}
for student, info in students.items():
    avg = 0
    for value in info["marks"]:
        avg = avg +value
    avg = avg/len(info["marks"])
    info["Average"] = avg
    if(avg >= 90):
        info["Grade"] = 'A'
    elif(avg >= 80):
        info["Grade"] = 'B'
    elif(avg >= 70):
        info["Grade"] = 'C'
    else :
        info["Grade"] = 'F'

for student, info in students.items():
    if(info["city"] == "Sukkur" and info["Grade"] == 'F'):
        print(student)
#print(students.keys(0))
# save = ""
for student, info in students.items():
    print(max(students[]["Average"],students = key.get))
        


SyntaxError: invalid syntax. Perhaps you forgot a comma? (344672416.py, line 29)

In [93]:
library = {
    "Fiction": {"books": ["Dune", "1984", "Brave New World"], "members": ["Ali", "Yusra", "Ali", "Hafsa"]},
    "Science": {"books": ["Cosmos", "Brief History", "Cosmos"], "members": ["Maria", "Sadia", "Maria"]},
    "History": {"books": ["Sapiens", "Guns Germs Steel"], "members": ["Ali", "Hafsa", "Sadia"]}
}
print("Total number of books: ")
count = 0
for genera, value in library.items():
    for i in value["books"]:
        count = count +1;
print(count)
print(library["Fiction"]["books"][0])
dup = ()
print("genera with duplicates: ")
for genera, value in library.items():
    has_dup = False
    for i in range(0,len(value["books"])):
        for j in range(i+1,len(value["books"])):
            if value["books"][i] == value["books"][j] :
                dup = list(dup)
                dup.append(value["books"][i])
                dup = tuple(dup)
                has_dup = True
    if (has_dup):
        print(genera)
print("duplicates: ")
print(dup)
set1 = {}
for genera, value in library.items():
    set1.clear()
    print(genera)
    set1 = set(value["members"])
    print("Members: ")
    print(set1)
All_members = []
for genera,value in library.items():
    for i in value["members"]:
        All_members.append(i)
print(All_members)
my_dict = {}
done = []
for i in range(0,len(All_members)):
    count = 1
    if(All_members[i] in done):
        continue
    for j in range(i+1,len(All_members)):
        if All_members[i] == All_members[j] :
            count = count+1
    my_dict[All_members[i]] = count
print("Appears most: ")
print(max(my_dict,key = my_dict.get))            

gen = []
for genera, value in library.items():
    set2 = set(value["members"])
    if len(set2)> 2:
        gen.append(genera)
gen = tuple(gen)
print(gen)

Total number of books: 
8
Dune
genera with duplicates: 
Science
duplicates: 
('Cosmos',)
Fiction
Members: 
{'Hafsa', 'Ali', 'Yusra'}
Science
Members: 
{'Sadia', 'Maria'}
History
Members: 
{'Hafsa', 'Ali', 'Sadia'}
['Ali', 'Yusra', 'Ali', 'Hafsa', 'Maria', 'Sadia', 'Maria', 'Ali', 'Hafsa', 'Sadia']
Appears most: 
Ali
('Fiction', 'History')


In [95]:
scores = [45, 82, 91, 55, 73, 91, 82, 45, 100, 55]
set1 = set(scores)
print(set1)

{100, 73, 45, 82, 55, 91}


In [96]:
import array

In [115]:
arr = array.array('i',[1,2,3])
print(arr)
print(arr.buffer_info())

array('i', [1, 2, 3])
(1948626074800, 3)


In [117]:
arr = array.array('s',["Yusra","Mango"])
print(arr)

ValueError: bad typecode (must be b, B, u, w, h, H, i, I, l, L, q, Q, f or d)

In [103]:
arr2 = array.array([1,2,2,4])
print(arr2)

TypeError: array() argument 1 must be a unicode character, not list

In [104]:
arr = array.array('i',(1,2,2,3))
print(arr)

array('i', [1, 2, 2, 3])


In [105]:
print(arr.count(2))

2


In [107]:
print(arr.index(1))

0


In [108]:
import numpy as np

In [110]:
arr = np.array([1,3,6])
print(arr)

[1 3 6]


In [112]:
#0d array
arr = np.array(1)
print(arr)
print(arr.ndim)
arr = np.array([1,2,3])
print(arr)
print(arr.ndim)
arr = np.array([
    [1,2],
    [3,4]
])
print(arr)
print(arr.ndim)
arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
print(arr)
print(arr.ndim)

1
0
[1 2 3]
1
[[1 2]
 [3 4]]
2
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [119]:
arr = np.array([1,2,3,4,5], ndmin=7)
print(arr)
print(arr.ndim)
for i in np.nditer(arr):
    print(i)

[[[[[[[1 2 3 4 5]]]]]]]
7
1
2
3
4
5


In [120]:
arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8


In [125]:
arr = np.array([10, 20, 30, 40, 50])
arr2 = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
print(arr.ndim)
print(arr2.ndim)

1
2


In [132]:
data = np.array([
    [11, 22, 33],
    [44, 55, 66],
    [77, 88, 99]
])
print(data.shape)
print(data.reshape(1,9))
print(data[:1][1:])

(3, 3)
[[11 22 33 44 55 66 77 88 99]]
[]


In [133]:
import pandas as pd
data = {
    "Name" : ["A","B",""],
    "Marks" : [23,45,67]
}
df = pd.DataFrame(data)

In [136]:
print(df)

  Name  Marks
0    A     23
1    B     45
2          67


In [137]:
ser = pd.Series([34,56,78])
print(ser)

0    34
1    56
2    78
dtype: int64


In [139]:
data = pd.read_csv('IMDB_Movies_Dataset.csv')
print(data.head())

   Unnamed: 0                                       Title  Average Rating  \
0           0                    The Shawshank Redemption             9.3   
1           1  Attack on Titan the Movie: The Last Attack             9.3   
2           2                               The Godfather             9.2   
3           3                              Hababam Sinifi             9.2   
4           4         Ramayana: The Legend of Prince Rama             9.2   

                             Director  \
0                      Frank Darabont   
1                    Yûichirô Hayashi   
2                Francis Ford Coppola   
3                       Ertem Egilmez   
4  Ram Mohan, Yûgô Sakô, Koichi Saski   

                                          Writer  Metascore  \
0                   Stephen King, Frank Darabont       82.0   
1  Natsuki Hanae, Yoshimasa Hosoya, Marina Inoue        NaN   
2               Mario Puzo, Francis Ford Coppola      100.0   
3                        Umur Bugay, R

In [140]:
data = pd.read_csv('retail_sales_dataset.csv')
print(data.head())

   Transaction ID        Date Customer ID  Gender  Age Product Category  \
0               1  2023-11-24     CUST001    Male   34           Beauty   
1               2  2023-02-27     CUST002  Female   26         Clothing   
2               3  2023-01-13     CUST003    Male   50      Electronics   
3               4  2023-05-21     CUST004    Male   37         Clothing   
4               5  2023-05-06     CUST005    Male   30           Beauty   

   Quantity  Price per Unit  Total Amount  
0         3              50           150  
1         2             500          1000  
2         1              30            30  
3         1             500           500  
4         2              50           100  


In [146]:
data = pd.read_csv('retail_sales_dataset.csv')
print(data["Date"].loc[0])
print(data.loc[0,"Date"])

2023-11-24
2023-11-24


In [149]:
dic = {
    "StudentID": [201, 202, 203, 204, 205],
    "Name": ["Ayesha", "Bilal", "Danish", "Hina", "Umar"],
    "Department": ["CS", "IT", "CS", "SE", "IT"],
    "Marks": [86,74,91,68,88],
    "Attendance": [90,82,96,78,92]
}
my_df = pd.DataFrame(dic)
print(my_df[my_df["Department"]=="IT"])

   StudentID   Name Department  Marks  Attendance
1        202  Bilal         IT     74          82
4        205   Umar         IT     88          92


In [156]:
df = pd.DataFrame({
    "Name": ["Ali", "Yusra", "Hafsa", "Sadia", "Maria"],
    "Marks": [85, 92, 55, 78, 91],
    "City": ["Karachi", "Sukkur", "Lahore", "Sukkur", "Karachi"]
})
print(df[0:3])
print(df["Name"])
print(df.shape)
print(df[df["Marks"] > 80])
print(df[(df["Marks"] > 80) & (df["City"] == "Sukkur")])

    Name  Marks     City
0    Ali     85  Karachi
1  Yusra     92   Sukkur
2  Hafsa     55   Lahore
0      Ali
1    Yusra
2    Hafsa
3    Sadia
4    Maria
Name: Name, dtype: str
(5, 3)
    Name  Marks     City
0    Ali     85  Karachi
1  Yusra     92   Sukkur
4  Maria     91  Karachi
    Name  Marks    City
1  Yusra     92  Sukkur


In [ ]:
df = pd.DataFrame({
    "Name": ["Ali", "Yusra", "Hafsa", "Sadia", "Maria", "Bilal"],
    "Marks": [85, 92, 55, 78, 91, None],
    "City": ["Karachi", "Sukkur", "Lahore", "Sukkur", "Karachi", "Lahore"],
    "Subject": ["Math", "Science", "Math", "Science", "Math", "Science"]
})