In [44]:
import pandas as pd
import numpy as np

In [48]:
data = {
    "ID" : [101,102,103,104,105],
    "Name" : ["Sara","Ahmed","John","Maria","Ali"],
    "Role" : ["AI Engineer","Data Analyst","ML Ops","AI Engineer","Data Analyst"],
    "Salary" : [95000,72000,88000,105000,65000],
    "Experience (Yrs)": [3,1,5,4,2]
}
df = pd.DataFrame(data)
df_filtered = df[(df["Role"] == "AI Engineer") & (df["Experience (Yrs)"]> 3)]
print(df_filtered)
print(df.groupby("Role")["Salary"].mean())
for x in df.index:
    if df.loc[x,"Experience (Yrs)"] >= 4:
        df.loc[x,"Level"]="Senior"
    else:
        df.loc[x,"Level"]="Junior"
print(df)

    ID   Name         Role  Salary  Experience (Yrs)
3  104  Maria  AI Engineer  105000                 4
Role
AI Engineer     100000.0
Data Analyst     68500.0
ML Ops           88000.0
Name: Salary, dtype: float64
    ID   Name          Role  Salary  Experience (Yrs)   Level
0  101   Sara   AI Engineer   95000                 3  Junior
1  102  Ahmed  Data Analyst   72000                 1  Junior
2  103   John        ML Ops   88000                 5  Senior
3  104  Maria   AI Engineer  105000                 4  Senior
4  105    Ali  Data Analyst   65000                 2  Junior


In [24]:
arr = np.random.randint(10,101,(5,5))
print("Original Array")
print(arr)
print("values greater than avg")
for i in np.nditer(arr):
    if i > arr.mean():
        print(i)
new_arr = arr
new_arr[new_arr < 50 ] = 0
print(new_arr)

Original Array
[[64 67 12 78 23]
 [35 89 64 61 51]
 [26 47 36 73 52]
 [36 58 24 22 52]
 [89 58 56 80 18]]
values greater than avg
64
67
78
89
64
61
51
73
52
58
52
89
58
56
80
[[64 67  0 78  0]
 [ 0 89 64 61 51]
 [ 0  0  0 73 52]
 [ 0 58  0  0 52]
 [89 58 56 80  0]]


In [55]:
df.loc[1,"Salary"] = None
print(df)
x = df["Salary"].median()
df["Salary"] = df["Salary"].fillna(x)
print(df)
df = df.sort_values(by="Salary",ascending = False)
print(df)

    ID   Name          Role    Salary  Experience (Yrs)   Level
3  104  Maria   AI Engineer  105000.0                 4  Senior
0  101   Sara   AI Engineer   95000.0                 3  Junior
1  102  Ahmed  Data Analyst       NaN                 1  Junior
2  103   John        ML Ops   88000.0                 5  Senior
4  105    Ali  Data Analyst   65000.0                 2  Junior
    ID   Name          Role    Salary  Experience (Yrs)   Level
3  104  Maria   AI Engineer  105000.0                 4  Senior
0  101   Sara   AI Engineer   95000.0                 3  Junior
1  102  Ahmed  Data Analyst   91500.0                 1  Junior
2  103   John        ML Ops   88000.0                 5  Senior
4  105    Ali  Data Analyst   65000.0                 2  Junior
    ID   Name          Role    Salary  Experience (Yrs)   Level
3  104  Maria   AI Engineer  105000.0                 4  Senior
0  101   Sara   AI Engineer   95000.0                 3  Junior
1  102  Ahmed  Data Analyst   91500.0   

In [49]:
print(df)

    ID   Name          Role  Salary  Experience (Yrs)   Level
0  101   Sara   AI Engineer   95000                 3  Junior
1  102  Ahmed  Data Analyst   72000                 1  Junior
2  103   John        ML Ops   88000                 5  Senior
3  104  Maria   AI Engineer  105000                 4  Senior
4  105    Ali  Data Analyst   65000                 2  Junior
